export {default as Hero} from './Hero'
export {default as Mailchimp} from './Mailchimp'
export {default as TextSection} from './TextSection'
export {default as ImageSection} from './ImageSection'
// export {default as ImageOnly} from './ImageOnly'
export {default as ContactUs} from './ContactUs'
export {default as SocialMedia} from './SocialMedia'
export {default as SearchPage} from './SearchPage'
export {default as Shipping} from './Shipping'
export {default as OrderForm} from './OrderForm'
export {default as HoursLocation} from './HoursLocation'
export {default as AboutUs} from './AboutUs'
export {default as OurFriends} from './OurFriends'
export {default as LandingLogo} from './LandingLogo'
export {default as Banner} from './Banner'

